### ISSUE TITLE
Source before/after history-substring-search?

### ISSUE THREAD

**Issue by infokiller** [tymm/zsh-directory-history#11]
Does it matter which plugin is loaded first?

**Comment by tymm** [comment]
You don't need to load history-substring-search at all if you source my plugin since my plugin contains a modified version of history-substring-search.

**Comment by polarathene** [comment]
@tymm Might be worth noting that on the README? Do you intend to sync updates from that repo when bugs are fixed?

**Comment by tymm** [comment]
@polarathene Just added that information to the README. Not sure what you mean with syncing?

**Comment by polarathene** [comment]
@tymm Thanks for that. Nothing in particular for me, there are issues and PRs though active and perhaps more in future. More concerned with autosuggestions/syntax highlighting bugs. Great plugin!
