### ISSUE TITLE
[Question/Bug] Can't find anything with () in it by typing ()

### ISSUE THREAD

**Issue by ShadowKyogre** [tymm/zsh-directory-history#16]
Hi there! I love zsh-directory-history so far (and the fact that it can be browsed using dirhist and dirlog for using in percol/peco).

However, I'm running into a slight hiccup.

Say we have a command like this:
`(){echo -ne "\e]1;$1\a"} imma_title`

I can find it by using "imma_title", but not by typing () itself. That makes it hard to go back through the history if I just want to take a look at the anonymous functions that I was testing.

**Comment by tymm** [comment]
Thank you for pointing this out.
I just fixed this issue.
