### ISSUE TITLE
Cursor not at end of line when recalling history

### ISSUE THREAD

**Issue by alanpearce** [tymm/zsh-directory-history#18]
With zsh's normal history, or history-substring-search, when I recall a command from history, the cursor is placed at the end of the line. With this plugin, the `directory-history-search-` commands go back one character. It's clear from https://github.com/tymm/zsh-directory-history/blob/d6d65c02cd2d39ad03334a5180b4f894ece58227/directory-history.plugin.zsh#L53 that this is a deliberate decision, but I don't understand why it is that way; it doesn't operate like any other history search.

An example, for clarification, using `|` to denote the cursor:

```
~
> echo test
test
```

When I use `directory-history-search-forward`:

```
~
> echo tes|t
```

When I use `up-line-or-history`, or `history-substring-search-up`:

```
~
> echo test|
```

I can of course submit a PR to change this behaviour, but it seems so deliberate, I wanted to check why it's that way.

**Comment by tymm** [comment]
Hello Alan,

if you submit a PR to change this behavior, I will happily accept it :)

The "problem" was that I always used zsh's vim mode, which made me think that having the cursor at the position of the last character is the normal behavior.
Just checked the default mode and realized it isn't ;)

Thanks.

**Comment by alanpearce** [comment]
Ah, in that case I can wrap the call in a check for vi-mode, then it should be sensible for everyone :)

**Comment by tymm** [comment]
I think there is no need for that.
Just removing the two occurrences of `zle vi-backward-char` seems to work just fine with all possibilities.
