### ISSUE TITLE
History location configurable?

### ISSUE THREAD

**Issue by polarathene** [tymm/zsh-directory-history#20]
The method `log_command` is where history is written to `~/.directory_history` right? Could that path be configured with variable like how [zsh-cmd-history](https://github.com/ericfreese/zsh-cwd-history) does with `$ZSH_CWD_HISTORY_DIR`? Perhaps `$ZSH_DIRECTORY_HISTORY_LOCATION`?

**Comment by tymm** [comment]
At the moment there is no wat to define where the history file is written to.
It is always `~/.directory_history`.
What would be the advantage to have that possibility?

**Comment by polarathene** [comment]
@tymm I like storing files out of home that I want to keep/backup as home can get pretty messy. Would it work fine if I use a symlink? I've read sometimes symlinks for dot files act up.

**Comment by tymm** [comment]
Sure, a symlink should be no problem at all.
