### ISSUE TITLE
Backing up history

### ISSUE THREAD

**Issue by N4M3Z** [tymm/zsh-directory-history#7]
Hello, thank you creating such an amazing plugin. If you would be so kind, could you please explain how is the per-directory history stored? Can it be merged and transferred to a machine not using the plugin? What steps do I need to take to backup my history for every folder? Thanks.

**Comment by tymm** [comment]
Thanks.
The complete history is stored into ~/.directory_history, so just backup that file if you want to backup the history.
It could be merged back to a normal .zsh_history by removing the directory information and making up timestamps (since my plugin doesn't save them and the normal zsh history seems to need timestamps).

**Comment by N4M3Z** [comment]
Thank you for the prompt answer. It might be useful to add this to the README file. Also, would you consider implementing timestamps? Or could you point me to a particular method where I can add this functionality?

**Comment by tymm** [comment]
You are right. I should add this information to the README.
Also adding timestamps makes sense. I will add both to the plugin next time I am working on it.
At the moment I am too busy with other projects.

For now you could write a small script which parses .directory_history, removes the directory information, appends fake ascending timestamps to every row and writes it into a file which then you can use as a .zsh_history.

**Comment by N4M3Z** [comment]
Thanks, that would be great. I think that in principle `.directory-history` should have identical format to standard ZSH history with the added bonus of directory separation. The way ZSH implements extended history logging looks like `:start:elapsed;command`:
```
": 1430177461:0;ls"
```
The timestamp can be printed in different formats using:
```
case $HIST_STAMPS in
    "mm/dd/yyyy") alias history='fc -fl 1' ;;
    "dd.mm.yyyy") alias history='fc -El 1' ;;
    "yyyy-mm-dd") alias history='fc -il 1' ;;
    *) alias history='fc -l 1' ;;
esac
```
[taken from `oh-my-zsh`]

Personally, I am aware of the following ZSH history options:
```
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing non-existent history.
```

**Comment by tymm** [comment]
Thank you for gathering that information. I will take it into account when I am working on the next version of the plugin.

**Comment by tymm** [comment]
I just implemented a new history format which includes a timestamp and is more similar to zsh's history.

**Comment by N4M3Z** [comment]
Epic, thanks. Testing now.

**Comment by N4M3Z** [comment]
It is working fine for me. However, there seems to be some overhead as my shell is now running significantly slower. Is this expected? I don't think it was this slow when I last used it.
Also, is there a fallback considered in case there is no history for the current directory? Or do I need to convert my current history by making up relevant directories and save to `.directory-history`?

**Comment by tymm** [comment]
The plugin will definitely make your shell slower. However it should not run slower than in the previous version.
Could you try out your history with the previous version to compare times and let me know?

No, there is no fallback for that case. I would suggest to start from a fresh .directory-history.
